name: Check Coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.6.1"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install prerequisites
        run: |
          poetry install --all-extras
          sudo ./scripts/install-taskwarrior.sh
          task --version
      - name: Coverage
        run: |
          poetry run coverage run -m pytest --doctest-modules
          poetry run coverage xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
